# data
dat_name: "enzyme" # enzyme, acidity, galaxy
save: TRUE

# mcmc params
sweeps: 100000
burnin: 100000

# hyperparameters
kappa_mult: 1 # multiple of 1/R^2 to use
a: 2
g: 0.2
h_mult: 10 # multiple of 1/R^2 to use
k_max: 30
delta: 1

# output configs
num_k_plot: 3  # how many values of k to show in pp plot
